# Configuración para Neon (Producción)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8085

#Para subir a render
# Tiempo máximo que una conexión puede estar inactiva antes de ser cerrada
spring.datasource.hikari.idle-timeout=60000
# Tiempo máximo de vida de una conexión
spring.datasource.hikari.max-lifetime=180000
# Prueba la conexión antes de darla a la app
spring.datasource.hikari.connection-test-query=SELECT 1